/** Install / offline plumbing for the PWA. Browser-only; safe to import but call from the client. */

import { getMeta, setMeta } from './settings.js';

export const isIOS = () => {
  const ua = navigator.userAgent;
  // iPadOS 13+ reports itself as a Mac with touch.
  return /iPad|iPhone|iPod/.test(ua) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
};

export const isStandalone = () => navigator.standalone === true || window.matchMedia?.('(display-mode: standalone)').matches === true;

/** iOS never offers an install prompt, so the "Add to Home Screen" instructions screen is ours to show. */
export async function shouldShowInstallHelp() {
  if (isStandalone()) return false;
  return !(await getMeta('installHelpDismissed', false));
}
export const dismissInstallHelp = () => setMeta('installHelpDismissed', true);

/**
 * Ask the browser not to evict our data under storage pressure. iOS honours this most reliably
 * for apps added to the Home Screen. Returns whether storage is persistent.
 */
export async function requestPersistentStorage() {
  try {
    if (!navigator.storage?.persist) return false;
    return (await navigator.storage.persisted()) || (await navigator.storage.persist());
  } catch {
    return false;
  }
}

/**
 * Register the service worker generated by vite-plugin-pwa (precaches the app shell so it works offline).
 * `onUpdate` is called when a new version has been installed and will apply on the next launch
 * (or immediately when `reload()` is called).
 */
export async function registerServiceWorker({ onOfflineReady, onUpdate } = {}) {
  if (!('serviceWorker' in navigator)) return { reload: () => {} };
  const { registerSW } = await import('virtual:pwa-register');
  const reload = registerSW({
    immediate: true,
    onOfflineReady: () => onOfflineReady?.(),
    onNeedRefresh: () => onUpdate?.(),
  });
  return { reload: () => reload(true) };
}
